---
- name: Instalar IBM MQ 9.3 (instalação padrão IBM)
  hosts: all
  become: true

  vars:
    mq_user: mqm
    mq_group: mqm
    mq_base_dir: /opt/mqm
    mq_home: /home/mqm
    mq_install_dir: "{{ mq_home }}/IBM_MQ"
    mq_pkg_local: "{{ mq_install_dir }}/9.3.0.0-IBM-MQTRIAL-LinuxX64.tar.gz"

    mq_rpms_required:
      - MQSeriesRuntime-9.3.0-0.x86_64.rpm
      - MQSeriesGSKit-9.3.0-0.x86_64.rpm
      - MQSeriesServer-9.3.0-0.x86_64.rpm
      - MQSeriesClient-9.3.0-0.x86_64.rpm
      - MQSeriesSamples-9.3.0-0.x86_64.rpm
      - MQSeriesMan-9.3.0-0.x86_64.rpm
      - MQSeriesSDK-9.3.0-0.x86_64.rpm

  tasks:

    - name: Validar conectividade SSH
      ansible.builtin.wait_for_connection:
        timeout: 10

    - name: Garantir dependências básicas instaladas
      ansible.builtin.dnf:
        name:
          - gcc
          - gcc-c++
          - make
          - pam
          - libstdc++
          - glibc
        state: present

    - name: Criar diretórios base (se ainda não existirem)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
        mode: '0755'
      loop:
        - "{{ mq_base_dir }}"
        - "{{ mq_install_dir }}"

    - name: Extrair pacote IBM MQ (caso ainda não extraído)
      ansible.builtin.unarchive:
        src: "{{ mq_pkg_local }}"
        dest: "{{ mq_install_dir }}"
        remote_src: true
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
      args:
        creates: "{{ mq_install_dir }}/MQServer"

    - name: Garantir permissões adequadas para instalação
      ansible.builtin.file:
        path: "{{ mq_install_dir }}"
        recurse: yes
        owner: root
        group: root
        mode: '0755'

    - name: Aceitar licença IBM MQ antes da instalação
      ansible.builtin.command: "./mqlicense.sh -accept"
      args:
        chdir: "{{ mq_install_dir }}/MQServer"
      changed_when: false
      ignore_errors: yes

    - name: Instalar pacotes essenciais do IBM MQ
      ansible.builtin.dnf:
        name: "{{ mq_install_dir }}/MQServer/{{ item }}"
        state: present
        disable_gpg_check: true
      loop: "{{ mq_rpms_required }}"

    - name: Aceitar licença IBM MQ pós-instalação
      ansible.builtin.command: "./mqlicense -accept"
      args:
        chdir: "/opt/mqm/bin"
      changed_when: false
      ignore_errors: yes

    - name: Verificar versão instalada
      ansible.builtin.command: /opt/mqm/bin/dspmqver
      register: mqver
      changed_when: false

    - name: Exibir versão instalada do IBM MQ
      ansible.builtin.debug:
        msg: "{{ mqver.stdout_lines }}"
