---
- name: Instalar IBM MQ 9.3 (instalação padrão IBM)
  hosts: all
  become: true

  vars:
    mq_user: mqm
    mq_group: mqm
    mq_base_dir: /opt/mqm
    mq_home: /home/mqm
    mq_bin_path: /opt/mqm/bin
    mq_install_dir: "{{ mq_home }}/IBM_MQ"
    # Fonte de download (alinhado ao s_install_mq.yml)
    repo_base_url: "http://54.196.155.119/repowmq/Linux"
    mq_fix_filename: "9.3.0.0-IBM-MQTRIAL-LinuxX64.tar.gz"
    mq_fix_url: "{{ repo_base_url }}/{{ mq_fix_filename }}"
    mq_pkg_local: "{{ mq_install_dir }}/download/{{ mq_fix_filename }}"
    # QMGR básico
    qmgr_name: "QM1"
    mq_listener_port: 1414
    mq_svrconn_channel: "SVRCONN.APP"
    mq_extra_users: []

    mq_rpms_required:
      - MQSeriesRuntime-9.3.0-0.x86_64.rpm
      - MQSeriesGSKit-9.3.0-0.x86_64.rpm
      - MQSeriesServer-9.3.0-0.x86_64.rpm
      - MQSeriesClient-9.3.0-0.x86_64.rpm
      - MQSeriesSamples-9.3.0-0.x86_64.rpm
      - MQSeriesMan-9.3.0-0.x86_64.rpm
      - MQSeriesSDK-9.3.0-0.x86_64.rpm

  tasks:

    - name: Validar conectividade SSH
      ansible.builtin.wait_for_connection:
        timeout: 10

    - name: Garantir dependências básicas instaladas
      ansible.builtin.dnf:
        name:
          - gcc
          - gcc-c++
          - make
          - pam
          - libstdc++
          - glibc
          - acl
        state: present

    - name: Criar grupo mqm
      ansible.builtin.group:
        name: "{{ mq_group }}"
        state: present

    - name: Criar usuário mqm
      ansible.builtin.user:
        name: "{{ mq_user }}"
        group: "{{ mq_group }}"
        home: "{{ mq_home }}"
        create_home: true
        shell: /bin/bash
        state: present

    - name: Criar diretório de download do instalador
      ansible.builtin.file:
        path: "{{ mq_install_dir }}/download"
        state: directory
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
        mode: '0755'

    - name: Definir nome do arquivo do instalador
      ansible.builtin.set_fact:
        mq_fix_file_resolved: "{{ mq_fix_filename }}"

    - name: Baixar instalador do IBM MQ
      ansible.builtin.get_url:
        url: "{{ mq_fix_url }}"
        dest: "{{ mq_install_dir }}/download/{{ mq_fix_file_resolved }}"
        mode: '0644'

    - name: Ajustar caminho do pacote local para unarchive
      ansible.builtin.set_fact:
        mq_pkg_local: "{{ mq_install_dir }}/download/{{ mq_fix_file_resolved }}"

    - name: Criar diretórios base (se ainda não existirem)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
        mode: '0755'
      loop:
        - "{{ mq_base_dir }}"
        - "{{ mq_install_dir }}"

    - name: Verificar existência do diretório MQServer
      ansible.builtin.stat:
        path: "{{ mq_install_dir }}/MQServer"
      register: mqserver_dir

    - name: Verificar se há RPMs em MQServer (antes da extração)
      ansible.builtin.find:
        paths: "{{ mq_install_dir }}/MQServer"
        patterns: "MQSeries*.rpm"
        file_type: file
      register: mqserver_rpms_before
      when: mqserver_dir.stat.exists | default(false)

    - name: Remover MQServer vazio/incompleto (sem RPMs) antes de extrair
      ansible.builtin.file:
        path: "{{ mq_install_dir }}/MQServer"
        state: absent
      when:
        - mqserver_dir.stat.exists | default(false)
        - (mqserver_rpms_before.matched | default(0) | int) == 0

    - name: Extrair pacote IBM MQ (caso ainda não extraído)
      ansible.builtin.unarchive:
        src: "{{ mq_pkg_local }}"
        dest: "{{ mq_install_dir }}"
        remote_src: true
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
        extra_opts:
          - "--overwrite"
      args:
        creates: "{{ mq_install_dir }}/MQServer/MQSeriesRuntime-9.3.0-0.x86_64.rpm"

    - name: Validar extração — verificar RPMs presentes em MQServer
      ansible.builtin.find:
        paths: "{{ mq_install_dir }}/MQServer"
        patterns: "MQSeries*.rpm"
        file_type: file
      register: mqserver_rpms

    - name: Falhar se RPMs do MQ não foram extraídos
      ansible.builtin.fail:
        msg: "Nenhum RPM encontrado em {{ mq_install_dir }}/MQServer. A extração pode ter falhado."
      when: mqserver_rpms.matched | default(0) | int == 0

    - name: Garantir permissões adequadas para instalação
      ansible.builtin.file:
        path: "{{ mq_install_dir }}"
        recurse: true
        owner: root
        group: root
        mode: '0755'

    - name: Aceitar licença IBM MQ antes da instalação
      ansible.builtin.command: "./mqlicense.sh -accept"
      args:
        chdir: "{{ mq_install_dir }}/MQServer"
      changed_when: false
      failed_when: false

    - name: Instalar pacotes essenciais do IBM MQ
      ansible.builtin.dnf:
        name: "{{ mq_install_dir }}/MQServer/{{ item }}"
        state: present
        disable_gpg_check: true
      loop: "{{ mq_rpms_required }}"

    - name: Aceitar licença IBM MQ pós-instalação
      ansible.builtin.command: "./mqlicense -accept"
      args:
        chdir: "/opt/mqm/bin"
      changed_when: false
      failed_when: false

    - name: Listar pacotes IBM MQ instalados (consulta dnf)
      ansible.builtin.command: dnf list installed | grep -E '^MQSeries'
      register: mq_rpms_installed
      changed_when: false
      failed_when: false

    - name: Exibir pacotes IBM MQ detectados
      ansible.builtin.debug:
        msg: "{{ mq_rpms_installed.stdout_lines | default(['Nenhum pacote MQSeries instalado.']) }}"

    - name: Instalar todos os RPMs do diretório (fallback)
      ansible.builtin.shell: |
        set -o pipefail
        dnf -y install {{ mq_install_dir }}/MQServer/*.rpm --nogpgcheck
      when: mq_rpms_installed.stdout is not defined or (mq_rpms_installed.stdout | trim) == ''
      register: dnf_fallback
      changed_when: true

    - name: Verificar existência do binário dspmqver
      ansible.builtin.stat:
        path: "{{ mq_bin_path }}/dspmqver"
      register: dspmqver_bin

    - name: Verificar versão instalada
      ansible.builtin.command: "{{ mq_bin_path }}/dspmqver"
      register: mqver
      changed_when: false
      when: dspmqver_bin.stat.exists | default(false)

    - name: Falhar se dspmqver não foi encontrado após instalação
      ansible.builtin.fail:
        msg: |
          dspmqver não encontrado em {{ mq_bin_path }}.
          A instalação dos pacotes IBM MQ pode não ter sido aplicada.
          Verifique os RPMs em {{ mq_install_dir }}/MQServer/ e reinstale se necessário.
      when: not (dspmqver_bin.stat.exists | default(false))

    - name: Exibir versão instalada do IBM MQ
      ansible.builtin.debug:
        msg: "{{ mqver.stdout_lines }}"

    - name: Criar Queue Manager básico se não existir
      ansible.builtin.command: "{{ mq_bin_path }}/crtmqm -u SYSTEM.DEAD.LETTER.QUEUE -lc -lf 4095 -lp 30 -ls 29 -q {{ qmgr_name }}"
      args:
        creates: "/var/mqm/qmgrs/{{ qmgr_name }}"
      become: true
      become_user: "{{ mq_user }}"

    - name: Garantir stanza Channels no qm.ini
      ansible.builtin.lineinfile:
        path: "/var/mqm/qmgrs/{{ qmgr_name }}/qm.ini"
        line: "Channels:"
        state: present
        create: true
        owner: "{{ mq_user }}"
        group: "{{ mq_group }}"
        mode: '0644'
      become: true

    - name: Definir MaxActiveChannels no qm.ini
      ansible.builtin.lineinfile:
        path: "/var/mqm/qmgrs/{{ qmgr_name }}/qm.ini"
        insertafter: "^Channels:$"
        line: "  MaxActiveChannels=5000"
      become: true

    - name: Definir MaxChannels no qm.ini
      ansible.builtin.lineinfile:
        path: "/var/mqm/qmgrs/{{ qmgr_name }}/qm.ini"
        insertafter: "^Channels:$"
        line: "  MaxChannels=5000"
      become: true

    - name: Iniciar Queue Manager
      ansible.builtin.command: "{{ mq_bin_path }}/strmqm {{ qmgr_name }}"
      become: true
      become_user: "{{ mq_user }}"
      register: strmqm_out
      changed_when: "'AMQ' in strmqm_out.stdout or 'AMQ' in strmqm_out.stderr"
      failed_when: false

    - name: Gerar MQSC com objetos básicos do QMGR
      ansible.builtin.copy:
        dest: "/tmp/{{ qmgr_name }}_base.mqsc"
        mode: '0644'
        content: |
          * Base definitions for {{ qmgr_name }}
          ALTER QMGR CCSID(1252) CHLAUTH(DISABLED)
          DEFINE CHANNEL({{ mq_svrconn_channel }}) CHLTYPE(SVRCONN) TRPTYPE(TCP) REPLACE
          DEFINE CHANNEL(CHANNEL1) CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
          DEFINE CHANNEL(MONITORACAO) CHLTYPE(SVRCONN) MCAUSER('mqm') REPLACE
          DEFINE LISTENER(LISTENER.TCP) TRPTYPE(TCP) CONTROL(QMGR) PORT({{ mq_listener_port }}) REPLACE
          START LISTENER(LISTENER.TCP)
          ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(OPTIONAL)
          SET CHLAUTH(*) TYPE(BLOCKUSER) USERLIST('MQADMIN') ACTION(REMOVE)
          REFRESH SECURITY TYPE(CONNAUTH)

    - name: Aplicar MQSC (objetos básicos)
      ansible.builtin.shell: "{{ mq_bin_path }}/runmqsc {{ qmgr_name }} < /tmp/{{ qmgr_name }}_base.mqsc"
      args:
        executable: /bin/bash
      become: true
      become_user: "{{ mq_user }}"
      register: mqsc_apply
      changed_when: "mqsc_apply.rc == 0"
      failed_when: false

    - name: Mostrar saída da aplicação MQSC
      ansible.builtin.debug:
        msg: "{{ mqsc_apply.stdout_lines }}"

    - name: Reiniciar Queue Manager para aplicar configurações de ini/MQSC
      ansible.builtin.shell: |
        {{ mq_bin_path }}/endmqm -i {{ qmgr_name }} || true
        {{ mq_bin_path }}/strmqm {{ qmgr_name }}
      become: true
      become_user: "{{ mq_user }}"
      register: restart_qm
      changed_when: "'AMQ' in restart_qm.stdout or 'AMQ' in restart_qm.stderr"
      failed_when: false

    - name: Adicionar usuários extras ao grupo mqm (opcional)
      ansible.builtin.user:
        name: "{{ item }}"
        groups: "{{ mq_group }}"
        append: true
      loop: "{{ mq_extra_users }}"
      when: mq_extra_users | length > 0
      become: true
