---
- name: "Automação Completa de Atualização IBM MQ - Versão {{ updatemq_version }}"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vars.yml
  
  tasks:
    - name: "Iniciando processo de atualização MQ"
      debug:
        msg: "=== INICIANDO AUTOMAÇÃO DE ATUALIZAÇÃO IBM MQ ==="
    
    - name: "Validar parâmetros obrigatórios"
      assert:
        that:
          - server_list is defined
          - updatemq_version is defined
        fail_msg: "Parâmetros obrigatórios não definidos"
        success_msg: "Parâmetros validados com sucesso"

- name: "ETAPA 1 - Validação e Acessibilidade"
  import_playbook: upfix1.yml

- name: "ETAPA 2 - Preparação de Logs e Diretórios"
  import_playbook: upfix2.yml

- name: "ETAPA 3 - Coleta de Visibilidade e Estado Atual"
  import_playbook: upfix3.yml

- name: "ETAPA 4 - Backup Completo do Sistema"
  import_playbook: backup_mq.yml

- name: "ETAPA 5 - Snapshot do Sistema"
  import_playbook: snapshot_system.yml

- name: "ETAPA 6 - Validações Pré-Atualização"
  import_playbook: pre_update_validation.yml

- name: "ETAPA 7 - Atualização do IBM MQ"
  import_playbook: update_mq.yml

- name: "ETAPA 8 - Validações Pós-Atualização"
  import_playbook: post_update_validation.yml

- name: "ETAPA 9 - Testes Funcionais"
  import_playbook: functional_tests.yml

- name: "ETAPA 10 - Notificação de Conclusão"
  import_playbook: send_notifications.yml
