---
- name: Instalação do IBM MQ 9.3 FP0031
  hosts: all
  become: true
  vars:
    mq_base_dir: "/tmp/mqInstall"
    repo_base_url: "http://54.196.155.119/repowmq/Linux"
    mq_user: "mqm"
    mq_bin_path: "/opt/mqm/bin"
    mq_fix_filename: "9.3.0.0-IBM-MQTRIAL-LinuxX64.tar.gz"
    mq_fix_url: "{{ repo_base_url }}/{{ mq_fix_filename }}"
  tasks:
    - name: Garantir diretório base existente
      ansible.builtin.file:
        path: "{{ mq_base_dir }}"
        state: directory
        mode: "0755"


    - name: Criar diretório temporário do fixpack
      ansible.builtin.file:
        path: "{{ mq_base_dir }}/mqfix"
        state: directory
        mode: "0755"

    - name: Definir nome do arquivo de fixpack
      ansible.builtin.set_fact:
        mq_fix_file_resolved: "{{ mq_fix_filename }}"

    - name: Baixar fixpack do IBM MQ
      ansible.builtin.get_url:
        url: "{{ mq_fix_url }}"
        dest: "{{ mq_base_dir }}/{{ mq_fix_file_resolved }}"
        mode: "0644"

    - name: Descompactar fixpack no diretório temporário
      ansible.builtin.unarchive:
        src: "{{ mq_base_dir }}/{{ mq_fix_file_resolved }}"
        dest: "{{ mq_base_dir }}/mqfix"
        remote_src: true

    - name: Descobrir lista de RPMs do MQ descompactados
      ansible.builtin.find:
        paths: "{{ mq_base_dir }}/mqfix"
        patterns: "MQSeries*.rpm"
        file_type: file
      register: mq_rpms

    - name: Falhar se nenhum RPM do MQ for encontrado
      ansible.builtin.fail:
        msg: "Nenhum pacote RPM do MQ encontrado após descompactar. Verifique o conteúdo do fixpack."
      when: mq_rpms.matched | default(0) | int == 0

    - name: Instalar pacotes IBM MQ (RPMs)
      ansible.builtin.package:
        name: "{{ item.path }}"
        state: present
      loop: "{{ mq_rpms.files }}"

    - name: Limpar diretório temporário do fixpack
      ansible.builtin.file:
        path: "{{ mq_base_dir }}/mqfix"
        state: absent

    - name: Remover arquivo de fixpack baixado
      ansible.builtin.file:
        path: "{{ mq_base_dir }}/{{ mq_fix_file_resolved }}"
        state: absent

    - name: Baixar script de criação do QMGR básico
      ansible.builtin.get_url:
        url: "{{ repo_base_url }}/crtQMGR_PRD.sh"
        dest: "{{ mq_base_dir }}/crtQMGR_PRD.sh"
        mode: "0755"

    - name: Executar criação do QMGR básico
      ansible.builtin.command: "{{ mq_base_dir }}/crtQMGR_PRD.sh"
      register: qmgr_create
      changed_when: "qmgr_create.rc == 0"

    - name: Exibir saída da criação do QMGR
      ansible.builtin.debug:
        var: qmgr_create.stdout

    - name: Verificar hostname
      ansible.builtin.command: hostname
      register: host_out
      changed_when: false

    - name: Verificar status das filas (dspmq)
      ansible.builtin.command: "{{ mq_bin_path }}/dspmq"
      become: true
      become_user: "{{ mq_user }}"
      register: dspmq_out
      changed_when: false
      failed_when: false

    - name: Verificar versão do MQ (dspmqver -f2)
      ansible.builtin.command: "{{ mq_bin_path }}/dspmqver -f2"
      become: true
      become_user: "{{ mq_user }}"
      register: dspmqver_out
      changed_when: false
      failed_when: false

    - name: Publicar facts do host e do IBM MQ
      ansible.builtin.set_fact:
        mq_hostname: "{{ host_out.stdout | default('n/d') }}"
        mq_status: "{{ dspmq_out.stdout | default('n/d') }}"
        mq_version: "{{ dspmqver_out.stdout | default('n/d') }}"

    - name: Exibir verificação final
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ mq_hostname }}"
          - "dspmq: {{ mq_status }}"
          - "dspmqver -f2: {{ mq_version }}"
