---
- name: Instalação do IBM MQ 9.3 em Windows
  hosts: windows
  gather_facts: false

  vars:
    # Caminhos e nomes padrão (ajuste conforme seu ambiente)
    repo_origin: 'http://54.196.155.119/repowmq/Windows'
    destination: "C:\\MQInstall"
    inst_pack: "9.4.4.0-IBM-MQ-Advanced-for-Developers-Win64.zip"
    inst_dir: "D:\\IBM\\MQ"

  tasks:
    # (verificação de versão removida para simplificar a instalação)

    - name: Garantir diretório de destino existe
      ansible.windows.win_file:
        path: "{{ destination }}"
        state: directory

    - name: Baixar instalador (9.4.4.0 Developers)
      ansible.windows.win_get_url:
        url: "{{ repo_origin }}/{{ inst_pack }}"
        dest: "{{ destination }}\\{{ inst_pack }}"
        force: false

    - name: Descompactar pacote de instalação
      community.windows.win_unzip:
        src: "{{ destination }}\\{{ inst_pack }}"
        dest: "{{ destination }}"
        delete_archive: false

    - name: Localizar MSI do IBM MQ após extração
      ansible.windows.win_find:
        paths: "{{ destination }}"
        patterns: "IBM MQ.msi"
        recurse: true
      register: mq_msi

    - name: Falhar se MSI não encontrado
      ansible.builtin.fail:
        msg: "Arquivo 'IBM MQ.msi' não encontrado após descompactar o instalador."
      when: mq_msi.matched | default(0) | int == 0

    - name: Instalar IBM MQ (MSI)
      ansible.windows.win_package:
        path: "{{ (mq_msi.files[0].path) | default('') }}"
        arguments: "/qn /norestart AGREETOLICENSE=\"yes\""
        state: present
        log_path: "{{ destination }}\\IBM_MQ_Install.log"

    # (coleta de versão pós-instalação removida para evitar dependência de módulos não disponíveis)


