---
- name: Instalação do IBM MQ 9.3 em Windows
  hosts: windows
  gather_facts: false

  vars:
    # Caminhos e nomes padrão (ajuste conforme seu ambiente)
    repo_origin: 'http://54.196.155.119/repowmq/Windows'
    destination: "C:\\MQInstall"
    inst_pack: "IBM_MQ_9.3_WINDOWS.zip"
    inst_ini: "MQInstall93.ini"
    inst_parm: "MQParms93.ini"
    inst_dir: "D:\\IBM\\MQ"

  tasks:
    - name: Obter versão instalada do IBM MQ (se existir)
      win_command: powershell.exe -NoProfile -NonInteractive -Command "dspmqver | findstr Version"
      register: mqver_cmd
      failed_when: false
      changed_when: false

    - name: Extrair versão instalada (se encontrada)
      ansible.builtin.set_fact:
        mq_version_instalada: "{{ (mqver_cmd.stdout.split(':') | last | default('') ) | trim }}"
      when: mqver_cmd.rc == 0 and 'Version' in (mqver_cmd.stdout | default(''))

    - name: Garantir diretório de destino existe
      ansible.windows.win_file:
        path: "{{ destination }}"
        state: directory

    - name: Baixar pacotes de instalação a partir do repositório HTTP
      ansible.windows.win_get_url:
        url: "{{ item.url }}"
        dest: "{{ destination }}\\{{ item.dest }}"
        force: false
      loop:
        - { url: "{{ repo_origin }}/MQ9.3/{{ inst_parm }}", dest: "{{ inst_parm }}" }
        - { url: "{{ repo_origin }}/MQ9.3/{{ inst_ini }}",  dest: "{{ inst_ini }}" }
        - { url: "{{ repo_origin }}/MQ9.3/{{ inst_pack }}", dest: "{{ inst_pack }}" }

    - name: Descompactar pacote de instalação
      community.windows.win_unzip:
        src: "{{ destination }}\\{{ inst_pack }}"
        dest: "{{ destination }}"
        delete_archive: false

    - name: Validar arquivos de instalação
      ansible.windows.win_stat:
        path: "{{ destination }}\\{{ item }}"
      register: inst_files
      loop:
        - "{{ inst_parm }}"
        - "{{ inst_ini }}"

    - name: Falhar se arquivos de instalação não encontrados
      ansible.builtin.fail:
        msg: "Installation Parm/Response file não encontrado. Instalação interrompida."
      when: (inst_files.results | selectattr('stat.exists','equalto', true) | list | length) < 2

    - name: Instalar IBM MQ (MSI)
      ansible.windows.win_package:
        path: "{{ destination }}\\IBM_MQ_9.3_WINDOWS\\MQServer\\MSI\\IBM MQ.msi"
        arguments: "/qn /norestart TRANSFORMS=\"{{ destination }}\\IBM_MQ_9.3_WINDOWS\\MQServer\\MSI\\1033.mst\" USEINI=\"{{ destination }}\\{{ inst_ini }}\" AGREETOLICENSE=\"yes\""
        state: present
        log_path: "{{ destination }}\\IBM_MQ_9_3_Install.log"

    - name: Coletar versão do IBM MQ após instalação
      win_command: powershell.exe -NoProfile -NonInteractive -Command "dspmqver"
      register: mqver_after
      changed_when: false
      failed_when: false

    - name: Publicar facts de versão
      ansible.builtin.set_fact:
        ibmmq_version_after: "{{ mqver_after.stdout | default('n/d') }}"

    - name: Mostrar versão final
      ansible.builtin.debug:
        msg: "Versão instalada do IBM MQ: {{ ibmmq_version_after }}"


