---
- name: Prepara e instala IBM MQ no mq01
  hosts: mqservers
  become: true
  environment:
    PATH: /opt/mqm/bin:{{ ansible_env.PATH }}
  collections:
    - ibm_messaging.ibmmq

  vars:
    # ajuste a versão/forma de fornecimento conforme seu cenário:
    # Exemplo 1: baixar automaticamente (internet habilitada no alvo)
    mq_version: 930

    # Exemplo 2: usar mídia local já copiada na máquina de controle
    # (comente as 2 linhas acima e descomente as abaixo)
    # downloadmq__local_source: true
    # downloadmq__mq_local_path: /caminho/para/mqadv_dev932_rhel_x86-64.tar.gz

    # IDs opcionais para o usuário de app; altere se precisar
    setupusers__app_uid: 909
    setupusers__app_gid: 909
    setupusers__mqm_home: /home/mqm
    setupusers__mqm_profile: .profile

    # nome do Queue Manager que você quer criar
    qm_name: QM1

  tasks:
    - name: Download do IBM MQ (ou uso de mídia local)
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.downloadmq
      vars:
        version: "{{ mq_version | default(omit) }}"
        local_source: "{{ downloadmq__local_source | default(false) }}"
        mq_local_path: "{{ downloadmq__mq_local_path | default(omit) }}"

    - name: Cria usuários/grupos e variáveis de ambiente
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.setupusers
      vars:
        app_uid: "{{ setupusers__app_uid }}"
        app_gid: "{{ setupusers__app_gid }}"
        mqm_home: "{{ setupusers__mqm_home }}"
        mqm_profile: "{{ setupusers__mqm_profile }}"

    - name: Instalação do IBM MQ
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.installmq

    - name: Ajusta/garante variáveis de ambiente do MQ
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.setupenvironment

    - name: (Opcional) Copiar um MQSC local para /var/mqm/dev-config.mqsc
      become_user: mqm
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.getconfig
      vars:
        # troque pelo seu arquivo MQSC se tiver um
        mqsc_local: ./files/dev-config.mqsc

    - name: (Opcional) Habilita console web
      become: true
      become_user: mqm
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.setupconsole

    - name: (Opcional) Inicia console web
      become: true
      become_user: mqm
      ansible.builtin.import_role:
        name: ibm_messaging.ibmmq.startconsole

    - name: Cria o Queue Manager
      become_user: mqm
      ibm_messaging.ibmmq.queue_manager:
        qmname: "{{ qm_name }}"
        state: present

    - name: (Opcional) Sobe o QM e aplica o MQSC
      become: true
      become_user: mqm
      ibm_messaging.ibmmq.queue_manager:
        qmname: "{{ qm_name }}"
        state: running
        mqsc_file: /var/mqm/dev-config.mqsc
      when: mqsc_local is defined

