---
- name: Validação de acessibilidade
  hosts: all
  gather_facts: no

  tasks:

    - name: Ação inicial
      debug:
        msg: "Iniciando validacao de acessibilidade no host {{ inventory_hostname }}"

    - name: Esperar 10 segundos
      wait_for:
        timeout: 10

    - name: Ação final
      debug:
        msg: "Simulação concluída no host {{ inventory_hostname }}"